### ISSUE TITLE
g:python_style in vimrc file is ignored

### ISSUE THREAD

**Issue by DigitalPig** [pixelneo/vim-python-docstring#1]
I found that even if I setup `let g:python_stype="numpy"` in the `.vimrc` file. It still uses google style.

My guess is because of the following lines:

https://github.com/pixelneo/vim-python-docstring/blob/60f58e343eb54439fe0cab91cf7818c46f9ebcc6/python/vimenv.py#L62-L64

**Comment by nettrino** [comment]
This is still an issue in lunarvim with the following config
```
  {
    'pixelneo/vim-python-docstring',
    config = function()
      vim.cmd("let g:python_style = 'numpy'")
    end,
  },
```
