### ISSUE TITLE
Vim 32 bits and Python 64 bit.

### ISSUE THREAD

**Issue by Ubaldo79** [pixelneo/vim-python-docstring#23]
I have this problem:

![image](https://user-images.githubusercontent.com/10845685/180258138-c8e2ac0e-43f9-4a96-a5d3-409c9179abdd.png)

May it be due to that I have Vim32 and Python (Anaconda) 64 bits? 

Unfortunately I have to cope with this setup since Vim64 does not seem to be well supported and at the same time I gotta work with the 64 bits of Anaconda. 

Any workaround?

**Comment by pixelneo** [comment]
Hello, I do not have Windows, so I can't reproduce it.
However, it seems that you vim does not have Python (try executing `:python3`).

**Comment by Ubaldo79** [comment]
I fixed it. The problem was not having/not having python 3 (which I had) but that vim only works with ONE python version which is the one it has been built for. 
For instance, I had python 3.9 but my version of vim was built with python 3.10, so ut won’t never work with anything else than 3.10. 

When I will update to 3.11, then I will have to download another version of vim as well.
