### ISSUE TITLE
Attributes are not in order

### ISSUE THREAD

**Issue by uthpalaherath** [pixelneo/vim-python-docstring#28]
Dear developer, 

First of all thanks for the great plugin! 

The attributes in the docstring don't seem to contain any order. Is it possible to set it such that it retains the original order they appear in the definition of the function?

![image](https://user-images.githubusercontent.com/28810161/192011766-d70bd31c-7ba6-49fe-a317-a5327223eb65.png)
![image](https://user-images.githubusercontent.com/28810161/192012003-9d254e33-0c2b-4e4b-8b45-2c3a35664675.png)

Thank you!

**Comment by pixelneo** [comment]
Hello, happy to hear you like it.
Thank you for reporting it, I'll have a look at it.

**Comment by uthpalaherath** [comment]
Thank you!

**Comment by pixelneo** [comment]
Hello, sorry for the delay, the issue should be fixed in the linked MR. (I'll merge, if it still persists, feel free to reopen the issue).
Have a nice day!

**Comment by uthpalaherath** [comment]
This is great! Thank you so much @pixelneo !
