### ISSUE TITLE
[Feature Request] remove the indent before the parameters in Numpy style

### ISSUE THREAD

**Issue by Fau818** [pixelneo/vim-python-docstring#32]
### The docstring generated by the plugin.

```python
"""

Parameters
----------
    foo1 :
    foo2 :
    ...

"""
```

### Expected result

```python
"""

Parameters
----------
foo1 :
foo2 :
...

"""
```

Is it possible to add an option for the user to choose? Or just change the default format.

**Comment by pixelneo** [comment]
Hello, yes it's possible. But you are of course correct, numpy style shouldn't have the indentation there. Thanks.

**Comment by pixelneo** [comment]
Should be fixed now.

**Comment by Fau818** [comment]
Thank you very much, I have updated the latest version and it works great!
