### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by dcrblack** [pixelneo/vim-python-docstring#36]
Hello,

Nice plugin by the way.

I've made some small error handling improvements to your plugin on my own machine that I would like to raise a PR for.

I've just improved how errors are logged mainly (no stack traces, just concise error messages).

If you happy with this I can raise a PR with your approval.

Cheers!

**Comment by pixelneo** [comment]
Hello, thank you, that would be great, error messaging needs improvement.

Cheers

**Comment by dcrblack** [comment]
@pixelneo I can't push my changes to a remote branch to be able to create a PR. I believe you need to give me permission to do so first.
