### ISSUE TITLE
No type for docstring

### ISSUE THREAD

**Issue by duskybomb** [pixelneo/vim-python-docstring#6]
Maybe I am missing something, but how can I add `type` along with `param`?

Example:
```python
def foo(foo_one, foo_two):
    """Function with reStructuredText style docstring

    :param foo_one:
    :type foo_one:
    :param foo_two:
    :type foo_two:
    """
    pass
```

**Comment by pixelneo** [comment]
Hello, 
you can modify `styles/rest-method.txt` in your repository clone by adding the `:type {{a}}:` line:
```
"""
{% if args|len > 0 %}{% for a in args %}:param {{a}}:
:type {{a}}:
{% endfor %}{% endif %}{% if returns %}:returns:
{% endif %}{% if yields %}:yields:
{% endif %}{% if raises|len > 0 %}{% for a in raises %}:raises {{a}}:
{% endfor %}{% endif %}"""
```

**Comment by duskybomb** [comment]
Thanks

I would like to add this as an option to the repository, would you mind if I make a PR? (by the end of this week)

**Comment by pixelneo** [comment]
Sure.
Probably, the easiest option would be to create a "new" style like `rest_typed` and adding two files `styles/rest_typed-method.txt` and `styles/rest_typed-class.txt`.

It would also be possible to add new option for Vim, which would apply only to reST docstrings. This would require more changes to the code.
